services:
  db:
    image: postgres:15-alpine
    container_name: pycrm-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pycrm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/src/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  redis:
    image: redis:7-alpine
    container_name: pycrm-redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: pycrm-api
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=pycrm
      - JWT_SECRET=supersecretkey123
      - JWT_REFRESH_SECRET=default_refresh
      - DATABASE_URL=postgres://postgres:password@db:5432/pycrm
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: pycrm-web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
